# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build:netlify"

# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"

# Enable prerendering for better SEO (Netlify automatically prerenders for bots)
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect www to non-www (after domain setup)
[[redirects]]
  from = "https://www.karniexim.com/*"
  to = "https://karniexim.com/:splat"
  status = 301
  force = true

# Headers for security and caching
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
